-- Run this script in your Supabase SQL Editor to set up the database

-- 1. Create the orders table
CREATE TABLE IF NOT EXISTS public.orders (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id text,
    customer_name text,
    items jsonb, -- Stores the cart items as a JSON array
    subtotal numeric,
    tax numeric,
    discount numeric DEFAULT 0,
    total numeric,
    amount_paid numeric,
    status text,
    payment_method text,
    created_at timestamptz DEFAULT now()
);

-- 2. Enable Row Level Security (RLS)
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;

-- 3. Create Policies to allow access
-- Policy for reading orders (Allow all for now, or restrict to auth users if you implement Supabase Auth)
CREATE POLICY "Enable read access for all users" ON public.orders
    FOR SELECT USING (true);

-- Policy for inserting orders
CREATE POLICY "Enable insert access for all users" ON public.orders
    FOR INSERT WITH CHECK (true);

-- Policy for updating orders (optional, if you need to update status)
CREATE POLICY "Enable update access for all users" ON public.orders
    FOR UPDATE USING (true);
